server:
  port: 9095

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/notifications
    username: notif_user
    password: notif_passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true